#!/usr/bin/env node
// Render every canonical skill into Claude, OpenAI, and Gemini formats under dist/.
import fs from 'node:fs';
import path from 'node:path';
import { loadAllSkills, DIST_DIR, ROOT, writeFile, copyDir, singleLine } from './lib/skills.mjs';
import {
  renderClaudeSkill,
  renderOpenAiInstructions,
  renderOpenApi,
  renderOpenAiTools,
  renderGeminiInstructions,
  renderGeminiFunctions,
} from './lib/render.mjs';

const skills = loadAllSkills();

if (skills.length === 0) {
  console.error('No skills found under skills/. Nothing to build.');
  process.exit(1);
}

fs.rmSync(DIST_DIR, { recursive: true, force: true });

const json = (obj) => `${JSON.stringify(obj, null, 2)}\n`;

// Skills reference shared/ docs with `../../../shared/…` (relative to skills/<domain>/<name>/).
// Each output target resolves that differently so an installed skill has no dead links:
//   Claude — bundle shared/ into the skill folder, link to `shared/…`
//   OpenAI/Gemini — no folder to bundle into (content is pasted), so link to the GitHub copy.
const SHARED_SRC = path.join(ROOT, 'shared');
const SHARED_URL = 'https://github.com/skuio/sku-skills/blob/main/shared/';
const localizeShared = (s) => s.replaceAll('../../../shared/', 'shared/');
const urlizeShared = (s) => s.replaceAll('../../../shared/', SHARED_URL);
const catalog = [];

for (const skill of skills) {
  const { domain, name, dir, meta } = skill;
  const slug = `${domain}/${name}`;

  // --- Claude: a self-contained Agent Skill folder -------------------------
  const claudeDir = path.join(DIST_DIR, 'claude', domain, name);
  writeFile(path.join(claudeDir, 'SKILL.md'), localizeShared(renderClaudeSkill(skill)));
  copyDir(path.join(dir, 'examples'), path.join(claudeDir, 'examples'));
  copyDir(SHARED_SRC, path.join(claudeDir, 'shared'));

  // --- OpenAI: GPT instructions + importable Action + function tools -------
  const openaiDir = path.join(DIST_DIR, 'openai', domain, name);
  writeFile(path.join(openaiDir, 'instructions.md'), urlizeShared(renderOpenAiInstructions(skill)));
  writeFile(path.join(openaiDir, 'action.openapi.json'), json(renderOpenApi(skill)));
  writeFile(path.join(openaiDir, 'tools.json'), json(renderOpenAiTools(skill)));

  // --- Gemini: system instructions + function declarations ----------------
  const geminiDir = path.join(DIST_DIR, 'gemini', domain, name);
  writeFile(path.join(geminiDir, 'system_instructions.md'), urlizeShared(renderGeminiInstructions(skill)));
  writeFile(path.join(geminiDir, 'function_declarations.json'), json(renderGeminiFunctions(skill)));

  catalog.push({
    name,
    domain,
    title: meta.title,
    version: meta.version,
    description: singleLine(meta.description),
    scopes: meta.auth.scopes,
    operations: meta.api.operations.length,
    tags: meta.tags ?? [],
    outputs: {
      claude: `dist/claude/${slug}/SKILL.md`,
      openai: `dist/openai/${slug}/`,
      gemini: `dist/gemini/${slug}/`,
    },
  });
}

// --- catalog + generated index ---------------------------------------------
writeFile(path.join(DIST_DIR, 'catalog.json'), json({ generatedFrom: 'skills/', count: catalog.length, skills: catalog }));

const byDomain = catalog.reduce((acc, s) => {
  (acc[s.domain] ??= []).push(s);
  return acc;
}, {});
const indexRows = Object.keys(byDomain)
  .sort()
  .map((domain) => {
    const rows = byDomain[domain]
      .map((s) => `| \`${s.name}\` | ${s.title} | ${s.description} | ${s.scopes.join(', ')} |`)
      .join('\n');
    return `### ${domain}\n\n| Skill | Title | Description | Scopes |\n| --- | --- | --- | --- |\n${rows}`;
  })
  .join('\n\n');
writeFile(
  path.join(DIST_DIR, 'README.md'),
  `# Built skills\n\n_Generated by \`npm run build\` — do not edit. Source of truth is \`skills/\`._\n\n${indexRows}\n`,
);

const rel = (p) => path.relative(ROOT, p);
console.log(`Built ${skills.length} skill(s) → ${rel(DIST_DIR)}/{claude,openai,gemini}`);
for (const s of catalog) {
  console.log(`  • ${s.domain}/${s.name}  (${s.operations} op${s.operations === 1 ? '' : 's'}, scopes: ${s.scopes.join(', ')})`);
}
